/*
 * motorAssociations.h
 *
 *  Created on: Mar 9, 2013
 *      Author: lutz
 */

#ifndef MOTORASSOCIATIONS_H_
#define MOTORASSOCIATIONS_H_

#include "motorIDs.h"

#define MOTORS_ALL { \
	MOTOR_HEAD_PITCH, \
	MOTOR_HEAD_TURN, \
	MOTOR_LEFT_ARM_PITCH, \
	MOTOR_RIGHT_ARM_PITCH, \
	MOTOR_LEFT_ARM_ROLL, \
	MOTOR_RIGHT_ARM_ROLL, \
	MOTOR_LEFT_ELBOW, \
	MOTOR_RIGHT_ELBOW,\
	MOTOR_STOMACH, \
	MOTOR_SPINE, \
	MOTOR_LEFT_HIP_ROLL, \
	MOTOR_RIGHT_HIP_ROLL, \
	MOTOR_LEFT_KNEE_TOP, \
	MOTOR_RIGHT_KNEE_TOP, \
	MOTOR_LEFT_KNEE_BOTTOM, \
	MOTOR_RIGHT_KNEE_BOTTOM, \
	MOTOR_LEFT_FOOT_ROLL, \
	MOTOR_RIGHT_FOOT_ROLL, \
	MOTOR_LEFT_FOOT_YAW, \
	MOTOR_RIGHT_FOOT_YAW, \
	}


#define MOTORS_TORSO { \
	MOTOR_HEAD_PITCH, \
	MOTOR_HEAD_TURN, \
	MOTOR_LEFT_ARM_PITCH, \
	MOTOR_RIGHT_ARM_PITCH, \
	MOTOR_LEFT_ARM_ROLL, \
	MOTOR_RIGHT_ARM_ROLL, \
	MOTOR_LEFT_ELBOW, \
	MOTOR_RIGHT_ELBOW \
	}


#define MOTORS_LEFT_LEG {\
	MOTOR_STOMACH, \
	MOTOR_LEFT_HIP_ROLL, \
	MOTOR_LEFT_KNEE_TOP, \
	MOTOR_LEFT_KNEE_BOTTOM, \
	MOTOR_LEFT_FOOT_ROLL, \
	MOTOR_LEFT_FOOT_YAW, \
	}

#define MOTORS_RIGHT_LEG {\
	MOTOR_SPINE, \
	MOTOR_RIGHT_HIP_ROLL, \
	MOTOR_RIGHT_KNEE_TOP, \
	MOTOR_RIGHT_KNEE_BOTTOM, \
	MOTOR_RIGHT_FOOT_ROLL, \
	MOTOR_RIGHT_FOOT_YAW, \
	}

#define MOTORS_FIRST_MOTOR_TORSO       MOTOR_HEAD_PITCH
#define MOTORS_FIRST_MOTOR_LEFT_LEG    MOTOR_STOMACH
#define MOTORS_FIRST_MOTOR_RIGHT_LEG   MOTOR_SPINE

#define MOTORS_LAST_MOTOR_TORSO        MOTOR_SPINE
#define MOTORS_LAST_MOTOR_LEFT_LEG     MOTOR_LEFT_FOOT_YAW
#define MOTORS_LAST_MOTOR_RIGHT_LEG    MOTOR_RIGHT_FOOT_YAW


#endif /* MOTORASSOCIATIONS_H_ */
