/*
 * msgIDs.h
 *
 *  Created on: 27.09.2011
 *      Author: lutz
 */

#ifndef MSGIDS_H_
#define MSGIDS_H_

typedef enum tag_msgID
{
	/* user */
	MSG_ID_GYRO_DATA_READY,
	MSG_ID_MAGNETO_RAW_DATA,
	MSG_ID_MAGNETO_SCALED_DATA,
	MSG_ID_ACCEL_RAW_DATA,
	MSG_ID_ACCEL_SCALED_DATA,
	MSG_ID_GYRO_RAW_DATA,
	MSG_ID_GYRO_SCALED_DATA,
	MSG_ID_IMU_SEND_DATA,
	MSG_ID_HEARTBEAT,
	MSG_ID_BAT_VOLTAGE,
	MSG_ID_REL_BAT_VOLTAGE,
	MSG_ID_TRIGGER_PUSH_MOTOR_VALUES,
	MSG_ID_TRIGGER_READ_MOTORS,

	MSG_ID_INCOMMING_DYNAMIXEL_PACKET,

	MSG_ID_TRIGGER_TIME_SYNC,

	MSG_ID_USER_MOTOR_SWITCH,

	MSG_ID_USR_BUTTON_1_PRESSED,
	MSG_ID_USR_BUTTON_2_PRESSED,
	MSG_ID_USR_BUTTON_3_PRESSED,
	MSG_ID_USR_BUTTON_4_PRESSED,

	MSG_ID_MOTOR_PWR_FAILURE,

	MSG_ID_DEMO_EXECUTE_TRIGGER,

	MSG_ID_DYNAMIXEL_FORWARDER_ISR_SWAP,

	/* system */
	MSG_LAST_ID
}msgID_t;


#endif /* MSGIDS_H_ */
